import type { GrowthRecommendation, ReviewSection } from "../types";

export const formatRecommendationAsText = (
  recommendation: GrowthRecommendation,
  reviewSections: ReviewSection[]
): string => {
  const lines: string[] = [];

  lines.push("YOUR GROWTH PLAN");
  lines.push("=".repeat(40));
  lines.push("");

  // Profile
  lines.push(
    `${recommendation.profile.stage} | ${recommendation.profile.model} | ${recommendation.profile.revenueBand} | ${recommendation.profile.primaryMotion}`
  );
  lines.push("");
  lines.push(recommendation.summary);
  lines.push("");

  // Primary bet
  const primaryBet = recommendation.bets[0];
  if (primaryBet) {
    lines.push("-".repeat(40));
    lines.push(`PRIMARY BET: ${primaryBet.title}`);
    lines.push("-".repeat(40));
    lines.push(primaryBet.rationale);
    lines.push(`Effort: ${primaryBet.effort} | Horizon: ${primaryBet.horizon}`);
    lines.push(`Channels: ${primaryBet.channels.join(", ")}`);
    lines.push("");
  }

  // Supporting bets
  const supportingBets = recommendation.bets.slice(1);
  if (supportingBets.length > 0) {
    lines.push("SUPPORTING BETS");
    for (const bet of supportingBets) {
      lines.push(`- ${bet.title} (${bet.effort} effort, ${bet.horizon})`);
      lines.push(`  ${bet.rationale}`);
    }
    lines.push("");
  }

  // Next steps
  lines.push("NEXT STEPS");
  recommendation.nextSteps.forEach((step, i) => {
    lines.push(`${i + 1}. ${step}`);
  });
  lines.push("");

  // Tools
  lines.push("SUGGESTED TOOLS");
  for (const tool of recommendation.suggestedTools) {
    lines.push(`- ${tool.name} (${tool.category}): ${tool.reason}`);
  }
  lines.push("");

  // Your answers
  lines.push("YOUR ANSWERS");
  for (const section of reviewSections) {
    lines.push(`- ${section.label}: ${section.value}`);
  }
  lines.push("");

  lines.push("Generated by Paperclip");

  return lines.join("\n");
};
