import { describe, expect, it } from "vitest";
import { createPlanInput, sanitizeAnswers } from "./questionnaire";
import { createGrowthRecommendation } from "./recommendations";
import { buildReviewSections } from "./onboardingFlow";
import { formatRecommendationAsText } from "./formatRecommendation";

const answers = sanitizeAnswers({
  businessStage: "launching",
  businessModel: "saas",
  monthlyRevenue: "2500",
  growthGoals: ["acquisition", "activation"],
  channels: ["seo", "outbound"],
  constraints: "Two founders, lean paid budget."
});

const recommendation = createGrowthRecommendation(createPlanInput(answers));
const reviewSections = buildReviewSections(answers);

describe("formatRecommendationAsText", () => {
  it("produces a non-empty string with key sections", () => {
    const text = formatRecommendationAsText(recommendation, reviewSections);

    expect(text).toContain("YOUR GROWTH PLAN");
    expect(text).toContain("PRIMARY BET:");
    expect(text).toContain("NEXT STEPS");
    expect(text).toContain("SUGGESTED TOOLS");
    expect(text).toContain("YOUR ANSWERS");
    expect(text).toContain("Generated by Paperclip");
  });

  it("includes profile information", () => {
    const text = formatRecommendationAsText(recommendation, reviewSections);

    expect(text).toContain("Launching");
    expect(text).toContain("SaaS product");
    expect(text).toContain("Early revenue");
  });

  it("includes all next steps as numbered items", () => {
    const text = formatRecommendationAsText(recommendation, reviewSections);

    for (let i = 1; i <= recommendation.nextSteps.length; i++) {
      expect(text).toContain(`${i}. `);
    }
  });
});
